theme: jekyll-theme-cayman
title: GitScope CLI
description: Generate beautiful Git commit summaries in HTML, JSON, or Markdown format
show_downloads: true
plugins:
  - jekyll-sitemap
include:
  - reports/
